package a2a.model;

import lombok.Data;
import lombok.ToString;

import java.util.HashMap;
import java.util.Map;

/**
 * Represents a tangible output generated by the agent during a task.
 * Artifacts are the results or products of the agent's work.
 */
@Data
@ToString
public class Artifact {
    /**
     * A descriptive name for the artifact (e.g., "Quarterly Sales Report.pdf", "Generated Logo Design", "analysis_results.json").
     * This name might be used by the client for display or identification.
     */
    private String name;
    /**
     * A human-readable description of the artifact. [CommonMark](https://commonmark.org/) MAY be used.
     */
    private String description;
    /**
     * An array containing the content of the artifact, broken down into one or more parts.
     * An artifact MUST contain at least one part.
     * Using multiple parts allows for complex artifacts (e.g., a report with embedded images or data tables).
     */
    private final Part[] parts;
    /**
     * A non-negative integer index for ordering artifacts or identifying artifact chunks during streaming.
     * Multiple artifacts (or artifact updates) can share the same index if they represent parts of the same logical output
     * that are being streamed or delivered separately.
     * Default: 0 if omitted.
     */
    private int index;
    /**
     * Used with streaming (`TaskArtifactUpdateEvent`):
     * If `true`, indicates this update's `parts` should be appended to the content of the artifact
     * currently identified by the same `index` value. This is useful for streaming textual data or
     * appending elements to a list in a `DataPart`.
     * If `false` or `null` (or omitted), this update replaces the artifact content at the given `index`.
     * This field is typically `false` for the first chunk of a streamed artifact.
     */
    private boolean append;
    /**
     * Used with streaming (`TaskArtifactUpdateEvent`):
     * If `true`, indicates this is the final update/chunk for the artifact at this `index`.
     * Signals the end of a streamed file or data structure.
     */
    private boolean lastChunk;
    /**
     * Arbitrary key-value metadata associated with the artifact.
     * Keys SHOULD be strings; values can be any valid JSON type.
     * Useful for creation timestamps, versioning info, checksums, etc.
     */
    private Map<String, Object> metadata = new HashMap<>();

//    public Artifact(Part[] parts) {
//        this.parts = Objects.requireNonNull(parts);
//    }
}
