package a2a.model;

import java.util.Map;

/**
 * Carries a new or updated artifact (or a chunk of an artifact) generated by the task during streaming.
 * This is one of the possible result types in a {@link SendTaskStreamingResponse}.
 */
public class TaskArtifactUpdateEvent {
    /**
     * The ID of the task that generated this artifact. This MUST match the `TaskSendParams.id`
     * from the `tasks/sendSubscribe` request that initiated this stream.
     */
    private String id;
    /**
     * The artifact data. This could be a complete artifact or an incremental chunk.
     * The client uses `artifact.index`, `artifact.append`, and `artifact.lastChunk`
     * to correctly assemble or update the artifact on its side.
     */
    private Artifact artifact;
    /**
     * Arbitrary metadata for this specific artifact update event.
     */
    private Map<String, Object> metadata;
}
